### ISSUE TITLE
Pyxspec install guide

### ISSUE THREAD

**Issue by ddennetiere** [biswajitmb/DarpanX#1]
Dear Sir, dear Madam,
I am very interested by DarpanX (I work in the SOLEIL Synchrotron in France) as I would like to develop a software for a periodic structure given a target. 
I find your requirement for PyXSpec, lacks a proper installation guide for PyXSpec. I only found the nasa page for the installation of XSPEC, but found no mention of pyxspec. Could you tell me how to install this package ? I'm running on windows 7. 

Thank you very much,
Dr. Dennetiere

**Comment by biswajitmb** [comment]
Dear Dr. Dennetiere,

Thank you very much for your interest in DarpanX.
Do you want to design a multilayer structure, for a given target profile of
reflectivity? If yes, then to some extent you can do that by DarpanX.

You can see the DarpanX paper for more about the software in the following
link.

https://doi.org/10.1016/j.ascom.2020.100446
OR
https://arxiv.org/abs/2101.02571

Regarding the PyXSPEC installation; you have to install the HEASOFT
package. PyXSPEC is a part of the HEASOFT. So, if you install HEASOFT then
PyXSPEC / XSPEC will automatically install in your system.
You can see the following links for the download and installation of
HEASOFT:

https://heasarc.gsfc.nasa.gov/lheasoft/

Note that, you can install the HEASOFT package only in the Linux / macOS
operating system.
If required please feel free to ask any questions/doubts regarding DarpanX.

With Regards,

Biswajit Mondal.
Email: biswajitm@prl.res.in

Physical Research Laboratory,
Ahmedabad, India.

**Comment by ddennetiere** [comment]
Thank you very much for this very quick answer.

Sadly I do not have a Unix OS. So I will look for a solution elsewhere. That is a shame because your work seems great and, yes, well suited too my needs.

Best regards,
David Dennetiere
Synchrotron SOLEIL, France

**Comment by biswajitmb** [comment]
You can install and use DarpanX in any operating system (including Windows), which supports Python 3. 
Only for the data (e.g., XRR data) fitting purpose, PyXSPEC is required.

I think your requirement is to design a multilayer structure and you can do it by using only DarpanX without the installation of the PyXSPEC.

After installing the DarpanX package it will be globally available in your system and easily you can import it into your python shell/script.

For the design of a multilayer structure with a required reflectivity (or other optical functions) profile, you can calculate the reflectivity in an iterative manner for different sets of multilayer parameters until your required profile is achieved. 
For that (with an automated and easy way), you have to import the DarpanX module into your Python script and then apply a 'loop' over the different combinations of your design parameters and calculate the optical functions (reflectivity) inside the loop until your requirement is achieved.   For more details, of how to call DarpanX inside your script/python-shell, you can look into the examples given in the DarpanX manual.


Thanks and Regards,
Biswajit

**Comment by ddennetiere** [comment]
That would be great ! That was my project indeed.
But i have tried intalling darpanx in my python/Lib/site-package folder but when I import it in my script I get the following error.
I thought it was because of the xspec missing dependency, but if you think I could still use it, I will ! Do you have any idea what's missing that would yield this traceback ?
`ValueError                                Traceback (most recent call last)
<ipython-input-1-0dc94c3d8041> in <module>
----> 1 import darpanx as drp

D:\Dennetiere\WinPython\WPy64-3850\python-3.8.5.amd64\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

D:\Dennetiere\WinPython\WPy64-3850\python-3.8.5.amd64\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

D:\Dennetiere\WinPython\WPy64-3850\python-3.8.5.amd64\lib\importlib\_bootstrap.py in _load_unlocked(spec)

D:\Dennetiere\WinPython\WPy64-3850\python-3.8.5.amd64\lib\importlib\_bootstrap.py in _load_backward_compatible(spec)

<frozen zipimport> in load_module(self, fullname)

D:\Dennetiere\WinPython\WPy64-3850\python-3.8.5.amd64\lib\site-packages\darpanx-0.4-py3.8.egg\darpanx\__init__.py in <module>
     26 from .wrapper_call import*
     27 import multiprocessing as mulp
---> 28 mulp.set_start_method('fork',force=True)
     29 #intro()

D:\Dennetiere\WinPython\WPy64-3850\python-3.8.5.amd64\lib\multiprocessing\context.py in set_start_method(self, method, force)
    245             self._actual_context = None
    246             return
--> 247         self._actual_context = self.get_context(method)
    248 
    249     def get_start_method(self, allow_none=False):

D:\Dennetiere\WinPython\WPy64-3850\python-3.8.5.amd64\lib\multiprocessing\context.py in get_context(self, method)
    237             return self._actual_context
    238         else:
--> 239             return super().get_context(method)
    240 
    241     def set_start_method(self, method, force=False):

D:\Dennetiere\WinPython\WPy64-3850\python-3.8.5.amd64\lib\multiprocessing\context.py in get_context(self, method)
    191             ctx = _concrete_contexts[method]
    192         except KeyError:
--> 193             raise ValueError('cannot find context for %r' % method) from None
    194         ctx._check_available()
    195         return ctx

ValueError: cannot find context for 'fork'`


Thank you very much for your help !!
Best regards,
David Dennetiere

**Comment by biswajitmb** [comment]
This error is not because of the missing PyXSPEC in your system. 
This is due to the incompatibility of the python multiprocessing 'fork' method in Windows OS. 

Thank you very much for pointing out this issue.
Now I have resolved it and updated in the DarpanX Git repository.
Please download the updated package and re-install it in your system. 

Hope it will work now. If you still facing a problem/getting some errors, please inform me.

Best Regards,
Biswajit.

**Comment by ddennetiere** [comment]
So I have pulled your commit c832e6 from github and the line "from  .darpanx_fit import *" has indeed disappeared. But the error remains. It is the same as previously posted.
For some reason, commit a3e3a26 doesn't pull but since the only change is in the manual, I guess it's ok. 

Again thank you very much for your answers and support, if I get to publish my code, I will give you a big shout out !

Best regards,
David Dennetiere

**Comment by biswajitmb** [comment]
I think some problems occur when I commit the changes in the git.
The main changes, I have done are inside "darpanx/__init.py__"  at the present lines 27 and 28. 
I have replaced the previous line with "mulp.set_start_method('fork',force=True)" to the new lines 27 and 28.
I guess, when you pulled the commits, these changes are not updated in your system.

After this correction, it is working fine in my windows-10 system without the error mentioned by you earlier.
So, I think you have to colon the repository from Git again. 
Or you can resolve it by commented out the line "mulp.set_start_method('fork',force=True)" inside "darpanx/__init.py__"  and then re-install the package by running "setup.py".

Thanks and Regards,
Biswajit

**Comment by ddennetiere** [comment]
That's it ! 
I have re-run the setup.py install, and it works like a charm !
Thank you a 1000 times again for your patience and for your work !

Best regards,
David Dennetiere
