### ISSUE TITLE
Stack order

### ISSUE THREAD

**Issue by ddennetiere** [biswajitmb/DarpanX#2]
Dear Biswajit Mondal,
I am very happy with you code, it is very nicely tied down!
But As I said, I am trying to genetically optimize my coating but It seems to be a problem with the representation of the coating in your code.
I am starting with a depth graded mirror :
`mirror_TM = drp.m=drp.Multilayer(MultilayerType="DepthGraded",SubstrateMaterial="SiO2",LayerMaterial=["Ru","B4C"],Repetition=100,D_max=26.4974757*2,D_min=8.64874803*2,C=0.203,GammaTop=0.5,Gamma=0.5,
SigmaValues=[0.1])`
and I am trying to replicate it with a user defined mirror: 
```
def depth_gradation(d0, a, b, N, gamma=0.5):
    thicknesses = np.empty((2*N,))
    for i in range(N):
        period = d0/(a+i+1)**b
        thicknesses[2*i] = period*gamma
        thicknesses[2*i+1] = period*(1-gamma)
    return thicknesses

period_number = 100
Z_array = depth_gradation(44, -0.6, 0.203, period_number)
mirror_DD=drp.Multilayer(MultilayerType="UserDefined",SubstrateMaterial="SiO2",LayerNum=period_number*2, 
                         LayerMaterial=["Ru","B4C"]*period_number,Z_Array=Z_array, ShowPar='No', SigmaValues=[1.0])
```
Both Ra match perfectly ! But the representation of the structure is upside down ! The thickest user defined layer seems to be of the bottom when the depth graded thickest layer is on the top, which is what I would expect.

Is that a glitch in darpanX ?

Thank you very much,
David

**Comment by biswajitmb** [comment]
Dear David,

The calculation employed in both the multilayer types is the same.
This is a visualization issue of the multilayer structures with the MultilayerType="UserDefined". I understand why it is happening.
I will resolve it soon and let you know. Thank you very much.

Best regards,
Biswajit

**Comment by biswajitmb** [comment]
I have resolved the visualization issue for MultilayerType="UserDefined" and updated it. Please pull the modification in your system and install it by running "setup.py install".

Thank you very much again,
Biswajit

**Comment by ddennetiere** [comment]
That fixed it !
Thank you !
I'm closing the issue.
